controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 200  # Hz
    
    legbot_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

legbot_position_controller:
  ros__parameters:
    use_sim_time: True
    joints:
      - lf_body_to_hip_joint
      - rf_body_to_hip_joint
      - lb_body_to_hip_joint
      - rb_body_to_hip_joint
      - lf_hip_to_upper_leg_joint
      - rf_hip_to_upper_leg_joint
      - lb_hip_to_upper_leg_joint
      - rb_hip_to_upper_leg_joint
      - lf_upper_leg_to_lower_leg_joint
      - rf_upper_leg_to_lower_leg_joint
      - lb_upper_leg_to_lower_leg_joint
      - rb_upper_leg_to_lower_leg_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      
    state_publish_rate: 20.0
    action_monitor_rate: 10.0
    
    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
    gains:
      lf_body_to_hip_joint: {p: 180, d: 0.9, i: 20}
      rf_body_to_hip_joint: {p: 180, d: 0.9, i: 20}
      lb_body_to_hip_joint: {p: 180, d: 0.9, i: 20}
      rb_body_to_hip_joint: {p: 180, d: 0.9, i: 20}
      lf_hip_to_upper_leg_joint: {p: 180, d: 0.9, i: 20}
      rf_hip_to_upper_leg_joint: {p: 180, d: 0.9, i: 20}
      lb_hip_to_upper_leg_joint: {p: 180, d: 0.9, i: 20}
      rb_hip_to_upper_leg_joint: {p: 180, d: 0.9, i: 20}
      lf_upper_leg_to_lower_leg_joint: {p: 180, d: 0.9, i: 20}
      rf_upper_leg_to_lower_leg_joint: {p: 180, d: 0.9, i: 20}
      lb_upper_leg_to_lower_leg_joint: {p: 180, d: 0.9, i: 20}
      rb_upper_leg_to_lower_leg_joint: {p: 180, d: 0.9, i: 20}
